title: <p align="center"> Roni Nakash </p>
logo: "/assets/img/ro-m.png?raw=true"

description:
  <p align="left">
  
  <img src="assets/img/g2.png" alt="Italian Trulli" style="width:15px;height:15px;">
  <a href="mailto:lorem@ipsum.com" style="font-size:18px;">Gmail</a> <br>  
  <img src="assets/img/l1.png" alt="Italian Trulli" style="width:15px;height:15px;">
  <a href="https://www.linkedin.com/in/roni-nakash/" style="font-size:18px;">LinkedIn</a> <br>  
  <img src="assets/img/geo3.png" alt="Italian Trulli" style="width:17px;height:17px;">
  <a style="font-size:18px;">Tel Aviv</a> <br>  
  <img src="assets/img/t1.png" alt="Italian Trulli" style="width:17px;height:17px;">
  <a style="font-size:17px;">(+972) 526634033</a> 
   
 

  </p>
  <p align="justify">
  I would love to hear your opinion :) <br>
  Feel free to contact me in any matter! <br>
  Cheers :)


  <br><br>
  <br><br>
  </p><br>
  
  <link rel="shortcut icon" type="x-icon" href="assets/img/f.ico">
show_downloads: false
google_analytics: G-NK5QYM5W74
theme: jekyll-theme-slate


