title: <p align="center"> Roni Nakash </p>
logo: /assets/img/ro-m.png <br>
description:
  <p align="center">
  <a href="pdf/resumedf">Resume</a> |
  <a href="https://www.linkedin.com/in/chrisknhtran/">LinkedIn</a> |
  <a href="https://github.com/chriskhanran">GitHub</a>
  </p>
  
  <p align="justify">
  I am pursing MS degree in Business Analytics at Simon Business School, University of Rochester.
  <br><br>
  I am currently a Machine Learning Research Intern at Skim AI Technologies with a focus on NLP and Deep Learning research.
  <br><br>
  </p><br>
show_downloads: true
google_analytics: G-NK5QYM5W74
theme: jekyll-theme-minimal
