title: <p align="center"> Roni Nakash </p>
logo: "/assets/img/ro-m.png?raw=true"

description:
  <p align="left">
  <a href="pdf/resumedf">Resume</a> <br>
 
  <img src="assets/img/g1.png" alt="Italian Trulli" style="width:17px;height:17px;">
  <a href="https://www.linkedin.com/in/chrisknhtran/" style="font-size:20px;">Gmail</a> <br>
  <img src="assets/img/l2.png" alt="Italian Trulli" style="width:17px;height:17px;">
  <a href="https://www.linkedin.com/in/chrisknhtran/" style="font-size:20px;">LinkedIn</a> <br>
  <img src="assets/img/geo2.png" alt="Italian Trulli" style="width:17px;height:17px;">
  <a href=" " style="font-size:20px;">Tel Aviv</a> <br>
  <img src="assets/img/t5.png" alt="Italian Trulli" style="width:17px;height:17px;">
  <a href=" " style="font-size:20px;">(+972) 526634033</a> <br>

  
  <a href="https://www.linkedin.com/in/chrisknhtran/">LinkedIn</a> |
  <img src="assets/img/e.png" alt="Italian Trulli" style="width:17px;height:17px;">
  <a href="https://github.com/chriskhanran">GitHub</a>
  <a href="https://github.com/chriskhanran" style="font-size:20px;">GitHub</a>
  <img src="assets/img/e.png" alt="Italian Trulli" style="width:20px;height:20px;">

  </p>
  <p align="justify">
  I am pursing MS degree in Bu

  <br><br>
  I am currently a Machine 
  <br><br>
  </p><br>
  
  <link rel="shortcut icon" type="x-icon" href="assets/img/f.ico">
show_downloads: false
google_analytics: G-NK5QYM5W74
theme: jekyll-theme-minimal


