logo: /assets/img/ro-m.png
title: <p align="center"> Roni Nakash </p>    
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics: G-NK5QYM5W74
theme: jekyll-theme-minimal
