title: <p align="center"> Roni Nakash </p>
logo: "/assets/img/ro-m.png?raw=true"

description:
  <p align="center">
  <a href="pdf/resumedf">Resume</a> <br>
  <a href="https://www.linkedin.com/in/chrisknhtran/">LinkedIn</a> |
  <a href="https://github.com/chriskhanran">GitHub</a>
  </p>
  <p align="justify">
  I am pursing MS degree in Bu

  <br><br>
  I am currently a Machine 
  <br><br>
  </p><br>
  
  <link rel="shortcut icon" type="image/x-icon" href="assets/img/f.ico">
show_downloads: false
google_analytics: G-NK5QYM5W74
theme: jekyll-theme-minimal


