title: <p align="center"> Roni Nakash </p>
logo: "/assets/img/ro-m.png?raw=true"

description:
  <p align="left">
  
  <img src="assets/img/g1.png" alt="Italian Trulli" style="width:17px;height:17px;">
  <a href="mailto:lorem@ipsum.com" style="font-size:20px;">Gmail</a> <br>
  <img src="assets/img/l2.png" alt="Italian Trulli" style="width:17px;height:17px;">
  <a href="https://www.linkedin.com/in/roni-nakash/" style="font-size:20px;">LinkedIn</a> <br>
  <img src="assets/img/geo3.png" alt="Italian Trulli" style="width:19px;height:19px;">
  <a href=" " style="font-size:20px;">Tel Aviv</a> <br>
  <img src="assets/img/t4.png" alt="Italian Trulli" style="width:18px;height:18px;">
  <a href=" " style="font-size:20px;">(+972) 526634033</a> <br>
  
 

  </p>
  <p align="justify">
  Hello and welcome to my portfolio! 
  My name is Roni Nakash, and I am a Data Scientist.
  I have a Master (MS.c) in Industrial Engineering (specialization in Data Science) and a bachelor (BS.c) in Industrial Engineering (specialization in information systems) from Ben Gurion University.
  In this portfolio, I will share with you some of my knowledge in the fields of Data Science, Machine Learning, Artificial Intelligence Statistics, Python and more.
  hope you will find this information helpful, and I would love to hear your opinion :)
  lease feel free to contact me in any matter!
  Cheers :)


  <br><br>
  I am currently a Machine 
  <br><br>
  </p><br>
  
  <link rel="shortcut icon" type="x-icon" href="assets/img/f.ico">
show_downloads: false
google_analytics: G-NK5QYM5W74
theme: jekyll-theme-minimal


